// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactDom from "react-dom";

function HomeIndexPage$MyHomeComponent(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Home Page Component"), React.createElement("p", undefined, String(match[0])), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (count) {
                                    return count + 1 | 0;
                                  }));
                    })
                }, "Increment Counter"));
}

var MyHomeComponent = {
  make: HomeIndexPage$MyHomeComponent
};

function run(param) {
  var root = document.querySelector("#reactRoot");
  if (!(root == null)) {
    ReactDom.render(React.createElement("div", undefined, React.createElement(HomeIndexPage$MyHomeComponent, {})), root);
    return ;
  }
  
}

export {
  MyHomeComponent ,
  run ,
  
}
/* react Not a pure module */
