// Generated by ReScript, PLEASE EDIT WITH CARE


function runRescript(param) {
  console.log("Hello to Rescript");
  console.log(/* Active */1);
  
}

export {
  runRescript ,
  
}
/* No side effect */
